[package]

name = "cttw"
version = "0.0.7"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]

[lib]
name = "cttw"
crate-type = ["dylib"]

[dependencies]
rust-crypto = "*"
rustc-serialize = "*"
twitter-api = "*"
oauth-client = "*"
