[package]

name = "cttw"
version = "0.0.2"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]

[lib]
name = "cttw"
crate-type = ["dylib"]

[dependencies]
rustc-serialize = "*"
twitter-api = "*"
oauth-client = "*"

[dependencies.rust-crypto]
git = "https://github.com/DaGenix/rust-crypto"
